# fulfillment_service/Dockerfile

# Base image
FROM node:18

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port that the service runs on
EXPOSE 3003

# Run the service
CMD ["npm", "start"]
